### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by eroux** [Esukhia/derge-kangyur-old#1]
We should have a paragraph on how to cite the eKangyur in a bibliography in a nice way (it's already been asked). I have to say I'm not really used to this kind of exercise but I'll think about it. 

Also, this would really ease the process if we upload it on [Zenodo](https://zenodo.org/), it would have a DOI that will then be citable easily. Zenodo now [supports versioning](http://blog.zenodo.org/2017/05/30/doi-versioning-launched/) so we can continue to fix errors after the upload. If we follow that road I'll make a small .sh script to prepare the upload, so that it's reproducible.

**Comment by ngawangtrinley** [comment]
![c](https://user-images.githubusercontent.com/17675331/43990148-21cbc09a-9d8a-11e8-8543-a9b9bbf17575.png)
![d](https://user-images.githubusercontent.com/17675331/43990149-22e786d0-9d8a-11e8-9ad3-8557a397232f.png)
