### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/derge-kangyur-old#2]
པོད།[ཤོག་གྲངས།] ཡིག་ནོར། --> ནོར་བཅོས།
______________
38[131a.7]  དེ་ལྟར་ཡངས་མ་ཀྱི་སྐད་ཅིག་ --> དེ་ལྟར་ཡང་སེམས་ཀྱི་སྐད་ཅིག་
22[161b.6] སྲིད་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཀྱི་ན་པ་སྟོང་ཟག་བརྒྱ་པ། པ་ཡང་ --> སྲིད་པ་ཡང་
22[46a.1] །ངོ་བོ་ཉིད་སྟོང་པ་ཀྱི་མཚན་མར་མྱི་རྟོག། --> །ངོ་བོ་ཉིད་སྟོང་པ་ཉིད་ཀྱི་མཚན་མར་མྱི་རྟོག།

**Comment by eroux** [comment]
81[287b.4] བུས་ེྩལ།  -> something valid (the sources are difficult to read)
