### ISSUE TITLE
plain text export

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/derge-kangyur-old#20]
...for ACTIB and other projects. An output format for pecha exchange.

**Comment by drupchen** [comment]
Élie Roux:
"it should be quite a straightforward adaptation of [https://github.com/Esukhia/derge-tengyur/blob/master/scripts/toTei.py](https://github.com/Esukhia/derge-tengyur/blob/master/scripts/toTei.py)"

**Comment by drupchen** [comment]
fixed in 4e9a92f7f5bfabb4deff13ea893368816b809714.

note: `toTei.py` was not used since works spanning across more than one volume needed to be accomodated.
