### ISSUE TITLE
broken syntax

### ISSUE THREAD

**Issue by eroux** [Esukhia/derge-kangyur-old#3]
I think the regexp process should be a bit more careful as it seems to break the markup. When executing

```
cd scripts
python3 toTei.py
```

a lot of syntax errors now appear, most of them in volume 6, by [this commit](https://github.com/Esukhia/derge-kangyur/commit/e9894f066f4d3f155f65df9b56c95bfadf2e52e0). Maybe there could be a commit review process? Or maybe some automated QA with an integrated tool like Travis-ci that would perform a few syntax checks? I think it's quite important not to completely remove the page tags, as the page numbering is not always linear.

**Comment by ngawangtrinley** [comment]
This is a one off error. The whole markup was completely stripped as part of some tests we do on local copies of the data.

**Comment by eroux** [comment]
thanks!
