### ISSUE TITLE
punctuation at beginning of text

### ISSUE THREAD

**Issue by eroux** [Esukhia/derge-kangyur-old#5]
the `toTei.py` script reports some (700) possible errors on punctuation at the beginning of texts, most of these could be addressed automatically but it depends on the policy that is chosen

**Comment by ngawangtrinley** [comment]
We just keep punctuation at beginning of texts, not of pages. We don't use ༑, for anything else we reflect what's on the paper.

**Comment by eroux** [comment]
what about beginning of volumes that are not beginning of texts? What about beginning of texts that are not marked by the usual punctuation in the original (ex: vol. 39 p. 237b)?

**Comment by ngawangtrinley** [comment]
We kept the ones at every beginning of volume, because of our superstitious insecurities, but they should go. for text without the usual punctuation I'd keep it as is and add the yig mgo as a correction.
